import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Audiophile",
  description: "Generated by Bilal Khan",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={"antialiased text-[0.938rem] leading-[1.563em]"}>
          {children}
        </body>
      </html>
    </>
  );
}
